// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIx-r3UBMlBveMPACxvKrr1zcxdr-ISag',
    appId: '1:257520399978:web:6f64e76ef8fa74a919fc13',
    messagingSenderId: '257520399978',
    projectId: 'worldscan-a53c3',
    authDomain: 'worldscan-a53c3.firebaseapp.com',
    storageBucket: 'worldscan-a53c3.firebasestorage.app',
    measurementId: 'G-06PHMBFMBY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwpgn3OhCTajzbajOs7ZlWrsNGi1TKxM4',
    appId: '1:257520399978:android:93864387678d996b19fc13',
    messagingSenderId: '257520399978',
    projectId: 'worldscan-a53c3',
    storageBucket: 'worldscan-a53c3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcmfSdrMdhgUzMQJLg2dFqEFZM_uJrQ8s',
    appId: '1:257520399978:ios:0842e43de3f23b5019fc13',
    messagingSenderId: '257520399978',
    projectId: 'worldscan-a53c3',
    storageBucket: 'worldscan-a53c3.firebasestorage.app',
    iosBundleId: 'com.example.worldScan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcmfSdrMdhgUzMQJLg2dFqEFZM_uJrQ8s',
    appId: '1:257520399978:ios:0842e43de3f23b5019fc13',
    messagingSenderId: '257520399978',
    projectId: 'worldscan-a53c3',
    storageBucket: 'worldscan-a53c3.firebasestorage.app',
    iosBundleId: 'com.example.worldScan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCIx-r3UBMlBveMPACxvKrr1zcxdr-ISag',
    appId: '1:257520399978:web:dc62a95ff2e8239b19fc13',
    messagingSenderId: '257520399978',
    projectId: 'worldscan-a53c3',
    authDomain: 'worldscan-a53c3.firebaseapp.com',
    storageBucket: 'worldscan-a53c3.firebasestorage.app',
    measurementId: 'G-SJH55SMYW6',
  );
}
